INGM-405: New example of using PDO poller
ingeniamc/ingeniamotion pull request #163
Opened 2024-04-10 09:35 UTC by WoodElv

### Example using PDO poller

### Description

The example establish a CoE communication, set a type of sensor for position and velocity feedback sensors, and read them using a poller with PDO.

### Type of change

- [x] Example using PDO poller.

### Tests
- [x] Unit test that checks all functions are called.

Please describe the tests that you run to verify your changes if it applies. 

### Documentation

Please update the documentation.

- [x] Use [type hints](https://docs.python.org/3/library/typing.html) for every function and argument.
- [ ] Build documentation locally to verify changes.

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingeniamotion tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2024-04-11 10:31 UTC, GullinBustin requested changes

2024-04-11 10:31 UTC, GullinBustin commented on examples/pdo_poller_example.py
> +    mc.configuration.set_velocity_feedback(SensorType.HALLS)
Why do you set HALLS sensor position and velocity feedbacks? This is the feedback with the worst resolution, it is an unusual case.

2024-04-11 10:31 UTC, GullinBustin commented on examples/pdo_poller_example.py
> +def establish_coe_connection(mc: MotionController) -> None:
Same as baudrate example, you can use our functions directly. Remember that exist these functions:

- connect_servo_ethercat_interface_index: https://distext.ingeniamc.com/doc/ingeniamotion/0.7.1/ingeniamotion/communication.html#ingeniamotion.communication.Communication.connect_servo_ethercat_interface_index
- connect_servo_ethercat_interface_ip: https://distext.ingeniamc.com/doc/ingeniamotion/0.7.1/ingeniamotion/communication.html#ingeniamotion.communication.Communication.connect_servo_ethercat_interface_ip

2024-04-11 10:42 UTC, mjedieckmann approved these changes

2024-04-11 10:42 UTC, mjedieckmann commented on examples/pdo_poller_example.py
> +def perform_pdo_poller(mc: MotionController) -> None:
"set_up" instead of "perform" sounds better

2024-04-12 10:25 UTC, GullinBustin approved these changes

2024-04-16 15:42 UTC, MartinALL91 commented on examples/pdo_poller_example.py
> +def set_feedback_sensors(mc: MotionController) -> None:
I don't think this is necessary.

2024-04-16 15:42 UTC, MartinALL91 commented on examples/pdo_poller_example.py
> +    interface_index = 3
I think its better if we use the interface IP address

2024-04-18 09:20 UTC, MartinALL91 approved these changes

2024-04-19 07:31 UTC, merged