Ingm 497 use fsoe state change callback instead of active wait
ingeniamc/ingeniamotion pull request #228
Opened 2024-08-21 14:27 UTC by polfeliu

[Doc]
https://novantamotion.atlassian.net/browse/INGM-497
https://docs.python.org/3/library/threading.html#event-objects

[Test]
Run fsoe example

2024-08-21 15:43 UTC, GullinBustin requested changes

2024-08-21 15:43 UTC, GullinBustin commented on ingeniamotion/fsoe.py
> +        State,
State should be included inside the TYPE_CHECKING if

2024-08-22 08:26 UTC, MartinALL91 approved these changes

2024-08-22 10:53 UTC, GullinBustin approved these changes

2024-08-22 13:39 UTC, merged