change is_sto1_active and is_sto2_active to booleans instead of ints
ingeniamc/ingeniamotion pull request #275
Opened 2024-11-08 09:17 UTC by polfeliu

Fixes INGM-532

### Type of change

Please add a description and delete options that are not relevant.

- [ ] change return type
- [ ] adapt tests
- [ ] Check wizard usage
- [ ] Check motionlab usage

### Documentation

Please update the documentation.

- [ ] Update docstrings of every function, method or class that change.
- [ ] USe [type hints](https://docs.python.org/3/library/typing.html) for every function and argument.
- [ ] Build documentation locally to verify changes.
- [ ] Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).

### Code formatting

- [ ] Use the ruff package to format the code: `ruff format ingeniamotion tests`.
- [ ] Use the ruff package to lint the code: `ruff check ingeniamotion`.

### Others

- [ ] Set fix version field in the Jira issue.

2024-11-08 11:11 UTC, GullinBustin requested changes

2024-11-08 11:11 UTC, GullinBustin commented on ingeniamotion/configuration.py
> +            returns False when the STO 1 input is inactive (bit is 1)
Be careful with docstring render in the docs:
![image](https://github.com/user-attachments/assets/14540fc3-fd4d-44e3-b9e7-bc6187e73b16)

2024-11-11 09:50 UTC, MartinALL91 approved these changes

2024-11-12 16:53 UTC, GullinBustin approved these changes

2024-11-13 08:31 UTC, merged