INGM-172 Fix commutation analysis feedbacks
ingeniamc/ingeniamotion pull request #33
Opened 2022-03-10 10:50 UTC by ArnauP

2022-03-11 10:51 UTC, GullinBustin requested changes

2022-03-11 10:51 UTC, GullinBustin commented on ingeniamotion/wizard_tests/base_test.py
> +        error_code_cleaned = error_code & self.WARNING_BIT_MASK
It should not be necessary, in get_last_buffer_error function, the error code hasn't warning bit. Check it, please.

2022-03-14 13:45 UTC, MartinALL91 commented on ingeniamotion/wizard_tests/base_test.py
> +        _, _, _, error_msg = self.mc.errors.get_error_data(
If you only want to get the last element of the tuple, you could do this `*_, error_msg = self.mc.errors.get_error_data()`

2022-03-15 13:20 UTC, GullinBustin approved these changes

2022-03-15 15:27 UTC, MartinALL91 approved these changes

2022-03-15 15:41 UTC, merged