INGM-168 create different test subclasses for feedbacks
ingeniamc/ingeniamotion pull request #60
Opened 2022-09-14 15:02 UTC by WoodElv

2022-09-14 15:48 UTC, MartinALL91 commented
You should resolve the conflicts with this branch

2022-09-14 16:58 UTC, GullinBustin requested changes

2022-09-14 16:58 UTC, GullinBustin commented on ingeniamotion/wizard_tests/absolute_encoder1_test.py
> +class AbsoluteEncoder1(Feedbacks):
In my opinion, the classes should have the with test in the name, AbsoluteEncoder1Test, for example. Same for all the classes, including the base one.

2022-09-15 13:26 UTC, GullinBustin requested changes

2022-09-15 13:26 UTC, GullinBustin commented on ingeniamotion/drive_tests.py
> +                          SensorType.QEI2: DigitalIncremental2Test(self.mc, servo, axis)}
Don't create the class instance inside the dictionary, create it after choosing it.

2022-09-15 13:26 UTC, GullinBustin commented on ingeniamotion/wizard_tests/feedbacks_tests/absolute_encoder2_test.py
> +    def feedback_setting(self):
Use parent function to avoid duplicate code

2022-09-15 13:26 UTC, GullinBustin commented on ingeniamotion/wizard_tests/feedbacks_tests/digital_hall_test.py
> +    def feedback_setting(self):
Use parent function to avoid duplicate code

2022-09-15 13:26 UTC, GullinBustin commented on ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
>          self.mc.configuration.set_auxiliar_feedback(auxiliary_sensor,
Set the sensor type directly

2022-09-15 13:26 UTC, GullinBustin commented on ingeniamotion/wizard_tests/feedbacks_tests/feedback_test.py
>              polarity_register, self.Polarity.NORMAL,
Set the register UID directly

2022-09-15 13:26 UTC, GullinBustin commented on ingeniamotion/drive_tests.py
> +                          SensorType.QEI2: DigitalIncremental2Test(self.mc, servo, axis)}
In addition, create a public function that gives the correct object initialized

2022-09-15 13:26 UTC, GullinBustin commented on ingeniamotion/drive_tests.py
> +        feedbacks_test = {SensorType.ABS1: AbsoluteEncoder2Test(self.mc, servo, axis),
Create this dictionary as a class atribute

2022-11-04 11:40 UTC, GullinBustin approved these changes

2022-11-18 12:37 UTC, GullinBustin approved these changes

2022-11-25 09:45 UTC, MartinALL91 approved these changes

2022-12-15 16:50 UTC, merged