Add exceptions in monitoring
ingeniamc/ingeniamotion pull request #65
Opened 2022-11-03 14:25 UTC by pzinemanas

Added missing exceptions to the monitoring when monitoring is not in a correct stage, or a timeout is reached.

2022-11-03 16:00 UTC, WoodElv approved these changes

2022-11-08 10:37 UTC, MartinALL91 requested changes

2022-11-08 10:37 UTC, MartinALL91 commented on tests/test_monitoring.py
> +        monitoring.read_monitoring_data()
I think that here you're testing if there is no data to read rather than if the monitoring is disabled.

2022-11-08 10:37 UTC, MartinALL91 commented on tests/test_monitoring.py
> +@pytest.mark.develop
I think this mark should not be here.

2022-11-08 10:37 UTC, MartinALL91 commented on tests/test_monitoring.py
> +def test_read_monitoring_data_non_mapped_registers(motion_controller, monitoring):
I don't think that you're testing if there are no mapped monitoring registers.

2022-11-23 15:11 UTC, GullinBustin requested changes

2022-11-23 15:14 UTC, GullinBustin requested changes

2022-11-23 15:14 UTC, GullinBustin commented on ingeniamotion/monitoring/base_monitoring.py
> +            IMMonitoringError: If monitoring is not ready.
Timeout exceptions should be added too

2022-12-20 11:10 UTC, GullinBustin commented
The issue will be reopen and will be done in the future

2022-12-20 11:10 UTC, closed without merging