INGM-203-fix-docstring-typing
ingeniamc/ingeniamotion pull request #69
Opened 2022-11-07 11:39 UTC by pzinemanas

This PR includes type-hints at the function signatures.

TODOs:

- [ ] Add type-hints at private functions
- [ ] Fix mypy errors

2022-11-08 13:34 UTC, MartinALL91 requested changes

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/drive_tests.py
> +    ):
The return type is missing.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/drive_tests.py
> +    ):
The return type is missing.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/errors.py
> +from typing import Optional
PEP8 import order.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/errors.py
> +    def __get_error_location(self, servo: str = DEFAULT_SERVO):
Return type missing.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/information.py
> +from ingenialink.register import Register, REG_ACCESS, REG_DTYPE
PEP8 import order.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/monitoring/base_monitoring.py
> +from typing import Optional, Union, Callable
PEP8 import order.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/motion_controller.py
> +from ingenialink.network import Network
PEP8 import order.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/motion_controller.py
> +            servo Ingenialink Network instance.
This is not clear. I think it should be "Network instance of the servo."

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/motion_controller.py
> +            servo Ingenialink Servo instance.
I think this should be "Servo instance."

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/motion.py
> +from typing import Optional
PEP8 import order.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/motion.py
> +    ):
Return type missing.

2022-11-08 13:34 UTC, MartinALL91 commented on ingeniamotion/motion.py
> +    ):
Return type missing.

2022-11-09 14:20 UTC, pzinemanas commented on ingeniamotion/disturbance.py
> +    def __init__(self, mc, servo: str = DEFAULT_SERVO):
Yes, I couldn't include it because I have to import the `MotionController` producing a circular import error. I don't know how to fix this yet.

2022-11-09 14:27 UTC, pzinemanas commented on ingeniamotion/disturbance.py
> +    def __init__(self, mc, servo: str = DEFAULT_SERVO):
Ok, now it's fixed :)

2022-11-23 08:35 UTC, WoodElv requested changes

2022-11-23 08:35 UTC, WoodElv commented on ingeniamotion/information.py
>      def __init__(self, motion_controller):
Lack of type hint

2022-12-20 12:08 UTC, WoodElv approved these changes

2022-12-22 17:19 UTC, GullinBustin requested changes
Before merge must be tested with python 3.6

2022-12-27 13:45 UTC, MartinALL91 approved these changes

2023-01-05 16:39 UTC, GullinBustin approved these changes

2023-01-09 09:12 UTC, merged