INGM-234 implement brake control test hotfix
ingeniamc/ingeniamotion pull request #70
Opened 2022-11-23 12:04 UTC by WoodElv

### Brake Control Test

### Description
The main purpose of this issue is to add a Brake tuning in current mode.
Optionally, an example is implemented to provide more facilities to test the new functionality.

### Type of change
- [x] Create a new class for a brake tuning

### Tests
- [ ] Optionally, an example.

2022-11-23 16:16 UTC, GullinBustin requested changes

2022-11-23 16:16 UTC, GullinBustin commented on ingeniamotion/wizard_tests/brake_tune.py
> +        finally:
finally is not necessary

2022-11-25 08:00 UTC, pzinemanas commented on ingeniamotion/wizard_tests/brake_tune.py
> +    report : dict
Just copy an example from another class ;)

2022-11-25 08:10 UTC, pzinemanas approved these changes

2022-12-14 12:58 UTC, MartinALL91 requested changes

2022-12-15 16:55 UTC, GullinBustin requested changes

2022-12-15 16:55 UTC, GullinBustin commented on ingeniamotion/wizard_tests/brake_tune.py
> +        axis (int)
Parameter descriptions are missing

2022-12-15 17:17 UTC, GullinBustin approved these changes

2022-12-15 17:17 UTC, merged